name: base_core
description: Um package auxiliar para manter as dependências globais de um aplicativo multi-repositório e mono-repositório.
homepage: https://www.github.com/leobidoous
repository: https://www.github.com/leobidoous/base_core
issue_tracker: https://www.github.com/leobidoous/base_core/issues
version: 1.4.2

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #===== Firebase depedencies ===================
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_database: ^12.0.2
  firebase_messaging: ^16.0.2
  firebase_analytics: ^12.0.2
  firebase_crashlytics: ^5.0.2
  firebase_remote_config: ^6.0.2
  firebase_in_app_messaging: 0.9.0+2
  #==============================================

  #===== New dependecies for new app flutter =====
  dio: ^5.9.0
  intl: ^0.20.2
  rxdart: ^0.28.0
  equatable: ^2.0.7
  local_auth: ^2.3.0
  share_plus: ^12.0.0
  geolocator: ^14.0.2
  path_provider: ^2.1.5
  local_auth_darwin: ^1.6.1
  connectivity_plus: ^7.0.0
  package_info_plus: ^8.3.1
  shared_preferences: ^2.5.3
  local_auth_android: ^1.0.53
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.2.4
  mask_text_input_formatter: ^2.9.0
  flutter_local_notifications: ^19.4.2
  #==============================================

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
